#!/usr/bin/env python
import sys
import subprocess

def main():
    subprocess.run("ci-skipper analysis", shell = True, executable="/bin/bash")
    sys.exit(0)  # Exit with a zero status code to indicate success

if __name__ == "__main__":
    main()