name: Workflow Failure Notification
on:
  workflow_run:
    workflows: ['*']
    types: [completed]
    branches: [main]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out'
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          args: "Workflow Failure Notification"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{
            "title": "Workflow ${{github.event.workflow_run.name}} ${{github.event.workflow_run.conclusion}} on ${{github.event.workflow_run.head_branch}}",
            "color": 16711680,
            "fields": [
              {"name": "Repository", "value": "[${{github.repository}}](${{github.server_url}}/${{github.repository}})", "inline": true},
              {"name": "Branch", "value": "${{github.event.workflow_run.head_branch}}", "inline": true},
              {"name": "Conclusion", "value": "${{github.event.workflow_run.conclusion}}", "inline": true}
            ],
            "url": "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}"}]'