name: Workspace - Check

on:
  workflow_dispatch:
  workflow_call:

jobs:
  workspace-check:
    runs-on: ubuntu-latest

    steps:
      - name: Build frontend
        uses: ./.github/actions/build-frontend
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          addArg: "--workspace"
  